# Generated by Django 5.2.12 on 2026-03-11 10:15

from django.db import migrations


def get_new_building(apps, schema_editor):
    new_building_year = 2015
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        if flat.construction_year >= new_building_year:
            flat.new_building = True
            flat.save()
        else:
            flat.new_building = False
            flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [
    migrations.RunPython(get_new_building)
    ]


