# Generated by Django 5.2.12 on 2026-03-11 11:21

from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_flat_complaint'),
    ]

    operations = [
    ]
