# Generated by Django 5.2.12 on 2026-03-11 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Жалоба'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст жалобы'),
        ),
    ]
