# Generated by Django 5.2.12 on 2026-03-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_flat_complaint_alter_flat_text'),
    ]

    operations = [
    ]
