# Generated by Django 5.2.12 on 2026-03-17 08:46

from django.db import migrations
import phonenumbers

def editing_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        formatted_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(formatted_number):
            flat.owner_pure_phone = phonenumbers.format_number(formatted_number, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
            flat.save()
        else:
            flat.owner_pure_phone = None
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_remove_flat_complaint_remove_flat_text_complaint_and_more'),
    ]

    operations = [
    migrations.RunPython(editing_number)
    ]
