# Generated by Django 5.2.12 on 2026-03-17 08:50

from django.db import migrations


def adding_records(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all().iterator():
        Owner.objects.get_or_create(
            owner=flat.owner,
            owner_pure_phone=flat.owner_pure_phone,
            owners_phonenumber=flat.owners_phonenumber)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20260317_1146'),
    ]

    operations = [
    migrations.RunPython(adding_records)
    ]
