# Generated by Django 5.2.12 on 2026-03-17 08:52

from django.db import migrations


def adding_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all().iterator():
        filter_flat = Flat.objects.filter(owner_pure_phone=owner.owner_pure_phone)
        for flat in filter_flat:
            owner.the_flat_are_owned.add(flat.id)
            owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20260317_1150'),
    ]

    operations = [
    migrations.RunPython(adding_flats)
    ]
