# Generated by Django 5.2.12 on 2026-03-17 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20260317_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='complaint_flat',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_claims', to='property.flat', verbose_name='Квартира, на которую жаловались'),
        ),
    ]
