# Generated by Django 5.2.12 on 2026-03-17 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20260317_1152'),
    ]

    operations = [
    ]
