# Generated by Django 5.2.12 on 2026-03-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_remove_flat_owner_remove_flat_owner_pure_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='text_complaint',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='flat',
            new_name='flats',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
